name: Prisma Demo CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile

      # Add Prisma Cloud vulnerability scanning step here
      # Example: Use Prisma Cloud Compute Scanner to scan the image

      # Add deployment steps to EKS here
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name prisma-cloud
          kubectl apply -f deployment.yaml --validate=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
